export const razasPerros: string[] = [
	"Sin Raza (Especial)",
    "Affenpinscher",
    "Afgano",
    "Airedale Terrier",
    "Akita",
    "Alaskan Malamute",
    "American Staffordshire Terrier",
    "Australian Cattle Dog",
    "Australian Shepherd",
    "Basenji",
    "Basset Hound",
    "Beagle",
    "Bearded Collie",
    "Beauceron",
    "Bichón Frisé",
    "Bloodhound",
    "Bobtail",
    "Border Collie",
    "Borzoi",
    "Boston Terrier",
    "Bóxer",
    "Boyero de Berna",
    "Braco Alemán",
    "Braco Italiano",
    "Briard",
    "Brittany",
    "Bull Terrier",
    "Bull Terrier Miniatura",
    "Bulldog",
    "Bulldog Americano",
    "Bulldog Francés",
    "Bullmastiff",
    "Cairn Terrier",
    "Cane Corso",
    "Caniche",
    "Cavalier King Charles Spaniel",
    "Chihuahua",
    "Chow Chow",
    "Clumber Spaniel",
    "Cocker Spaniel Americano",
    "Cocker Spaniel Inglés",
    "Collie",
    "Collie Barbudo",
    "Coonhound",
    "Coonhound Negro y Tan",
    "Corgi Cardigan",
    "Corgi Pembroke",
    "Coton de Tulear",
    "Dachshund",
    "Dálmata",
    "Dandie Dinmont Terrier",
    "Doberman",
    "Dogo Argentino",
    "Dogo de Burdeos",
    "Elkhound Noruego",
    "English Setter",
    "Epagneul Bretón",
    "Fila Brasileiro",
    "Fox Terrier",
    "Foxhound Americano",
    "Foxhound Inglés",
    "Galgo Español",
    "Galgo Italiano",
    "Golden Retriever",
    "Gran Danés",
    "Gran Pirineo",
    "Greyhound",
    "Grifón de Bruselas",
    "Harrier",
    "Havanese",
    "Husky Siberiano",
    "Irish Setter",
    "Irish Terrier",
    "Irish Water Spaniel",
    "Irish Wolfhound",
    "Jack Russell Terrier",
    "Japanese Chin",
    "Japanese Spitz",
    "Keeshond",
    "Kerry Blue Terrier",
    "Komondor",
    "Kuvasz",
    "Labrador Retriever",
    "Lagotto Romagnolo",
    "Lakeland Terrier",
    "Leonberger",
    "Lhasa Apso",
    "Maltés",
    "Manchester Terrier",
    "Mastín Español",
    "Mastín Inglés",
    "Mastín Napolitano",
    "Mudi",
    "Norfolk Terrier",
    "Norwich Terrier",
    "Nova Scotia Duck Tolling Retriever",
    "Otterhound",
    "Papillon",
    "Pastor Alemán",
    "Pastor Australiano",
    "Pastor Belga",
    "Pastor de Shetland",
    "Pekinés",
    "Perdiguero de Drente",
    "Perdiguero Portugués",
    "Petit Basset Griffon Vendéen",
    "Pharaoh Hound",
    "Pinscher Miniatura",
    "Pitbull",
    "Pointer Inglés",
    "Pomerania",
    "Presa Canario",
    "Pug",
    "Puli",
    "Pumi",
    "Rhodesian Ridgeback",
    "Rottweiler",
    "Saluki",
    "Samoyedo",
    "San Bernardo",
    "Schipperke",
    "Schnauzer Gigante",
    "Schnauzer Miniatura",
    "Scottish Terrier",
    "Sealyham Terrier",
    "Setter Inglés",
    "Shar Pei",
    "Shiba Inu",
    "Shih Tzu",
    "Silky Terrier",
    "Sin Raza (Especial)",
    "Skye Terrier",
    "Soft Coated Wheaten Terrier",
    "Spaniel Tibetano",
    "Spitz Alemán",
    "Springer Spaniel Inglés",
    "Staffordshire Bull Terrier",
    "Sussex Spaniel",
    "Terranova",
    "Terrier Australiano",
    "Terrier Checo",
    "Terrier Escocés",
    "Terrier Galés",
    "Terrier Irlandés",
    "Terrier Tibetano",
    "Tosa Inu",
    "Vizsla",
    "Weimaraner",
    "West Highland White Terrier",
    "Whippet",
    "Xoloitzcuintle",
    "Yorkshire Terrier"
];

export const razasGatos: string[] = [
	"Sin Raza (Especial)",
    "Abisinio",
    "American Bobtail",
    "American Curl",
    "American Shorthair",
    "American Wirehair",
    "Asiático",
    "Australian Mist",
    "Balinés",
    "Bengalí",
    "Birmano",
    "Bobtail Japonés",
    "Bombay",
    "British Longhair",
    "British Shorthair",
    "Burmés",
    "Burmilla",
    "Cartujo (Chartreux)",
    "Chantilly-Tiffany",
    "Chausie",
    "Colorpoint Shorthair",
    "Cornish Rex",
    "Cymric",
    "Devon Rex",
    "Don Sphynx",
    "Egipcio Mau",
    "Exótico de Pelo Corto",
    "Habana Brown",
    "Himalayo",
    "Javanese",
    "Khao Manee",
    "Korat",
    "LaPerm",
    "Maine Coon",
    "Manx",
    "Mau Árabe",
    "Munchkin",
    "Nebelung",
    "Norwegian Forest",
    "Ocigato",
    "Oriental",
    "Persa",
    "Peterbald",
    "Pixie-Bob",
    "Ragamuffin",
    "Ragdoll",
    "Rex Alemán",
    "Ruso Azul",
    "Safari",
    "Savannah",
    "Scottish Fold",
    "Selkirk Rex",
    "Serengeti",
    "Siberiano",
    "Siamés",
    "Sin Raza (Especial)",
    "Singapura",
    "Snowshoe",
    "Sokoke",
    "Somalí",
    "Sphynx",
    "Tonkinés",
    "Toyger",
    "Turco Angora",
    "Turco Van"
];